/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalasRouteImport } from './routes/salas'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ApresentadoresRouteImport } from './routes/apresentadores'
import { Route as IndexRouteImport } from './routes/index'

const SalasRoute = SalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentadoresRoute = ApresentadoresRouteImport.update({
  id: '/apresentadores',
  path: '/apresentadores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentadores': typeof ApresentadoresRoute
  '/reservas': typeof ReservasRoute
  '/salas': typeof SalasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentadores': typeof ApresentadoresRoute
  '/reservas': typeof ReservasRoute
  '/salas': typeof SalasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apresentadores': typeof ApresentadoresRoute
  '/reservas': typeof ReservasRoute
  '/salas': typeof SalasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apresentadores' | '/reservas' | '/salas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apresentadores' | '/reservas' | '/salas'
  id: '__root__' | '/' | '/apresentadores' | '/reservas' | '/salas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresentadoresRoute: typeof ApresentadoresRoute
  ReservasRoute: typeof ReservasRoute
  SalasRoute: typeof SalasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salas': {
      id: '/salas'
      path: '/salas'
      fullPath: '/salas'
      preLoaderRoute: typeof SalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentadores': {
      id: '/apresentadores'
      path: '/apresentadores'
      fullPath: '/apresentadores'
      preLoaderRoute: typeof ApresentadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresentadoresRoute: ApresentadoresRoute,
  ReservasRoute: ReservasRoute,
  SalasRoute: SalasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
